source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
   use_frameworks!
   pod 'Alamofire', '~> 2.0.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'master'
pod 'Socket.IO-Client-Swift', '~> 4.1.2'




